# Generated by Django 4.0.8 on 2023-11-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coingecko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onp',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
