# Generated by Django 4.0.8 on 2023-11-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coingecko', '0003_alter_onp_token_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onp',
            old_name='price_change',
            new_name='price_change_24hr',
        ),
        migrations.AddField(
            model_name='onp',
            name='price_change_7d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
