# Generated by Django 4.0.8 on 2023-11-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coingecko', '0004_rename_price_change_onp_price_change_24hr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeckoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
