# Generated by Django 4.0.8 on 2023-11-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coingecko', '0007_remove_geckotoken_address_address_chain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckotoken',
            name='token_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
