# Generated by Django 4.0.8 on 2023-11-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coingecko', '0008_geckotoken_token_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='contract',
        ),
    ]
