# Generated by Django 4.0.8 on 2023-12-13 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coingecko', '0009_rename_address_address_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='geckotoken',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geckotoken',
            name='price_change_24hr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='geckotoken',
            name='price_change_7d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='geckotoken',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geckotoken',
            name='symbol',
            field=models.CharField(default='', max_length=255),
        ),
    ]
