# Generated by Django 4.0.8 on 2023-12-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coingecko', '0012_address_decimals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geckotoken',
            name='price_change_24hr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='geckotoken',
            name='price_change_7d',
            field=models.FloatField(default=0),
        ),
    ]
