# Generated by Django 4.0.8 on 2024-01-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coingecko', '0014_geckofilter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geckofilter',
            old_name='percentage_change_24h',
            new_name='percent_change_24h',
        ),
        migrations.RenameField(
            model_name='geckofilter',
            old_name='percentage_change_7d',
            new_name='percent_change_7d',
        ),
    ]
