# Generated by Django 4.0.8 on 2024-01-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coingecko', '0015_rename_percentage_change_24h_geckofilter_percent_change_24h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
