# Generated by Django 4.2.9 on 2024-02-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coingecko', '0016_address_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geckotoken',
            name='token_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
