# Generated by Django 4.0.8 on 2023-12-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('abi', models.TextField(default='')),
                ('chain', models.TextField(default='')),
                ('version', models.IntegerField(default=0)),
            ],
        ),
    ]
