# Generated by Django 4.0.8 on 2024-01-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_alter_factorycontract_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(default='', max_length=255)),
                ('chain', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
