# Generated by Django 4.0.8 on 2024-01-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_webhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(default='', max_length=255)),
                ('chain', models.CharField(default='', max_length=255)),
                ('max_address', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Webhook',
        ),
    ]
