# Generated by Django 4.0.8 on 2024-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_addresswebhook_delete_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorycontract',
            name='chain',
            field=models.CharField(choices=[('ethereum', 'ethereum'), ('binance-smart-chain', 'binance-smart-chain'), ('polygon-pos', 'polygon-pos'), ('arbitrum-one', 'arbitrum-one'), ('base', 'base'), ('avalanche', 'avalanche'), ('solana', 'solana')], default='', max_length=255),
        ),
    ]
