# Generated by Django 4.1.7 on 2024-01-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(default='', max_length=255)),
                ('chain', models.CharField(default='', max_length=255)),
                ('token1', models.CharField(default='', max_length=255)),
                ('token2', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='bot',
            old_name='chain',
            new_name='address',
        ),
        migrations.AddField(
            model_name='bot',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(default='', max_length=255)),
                ('transaction_type', models.CharField(default='', max_length=255)),
                ('amount_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gas_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_bot.pool')),
            ],
        ),
        migrations.AddField(
            model_name='pool',
            name='bot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading_bot.bot'),
        ),
    ]
