# Generated by Django 4.0.8 on 2023-11-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0024_remove_token_chain_remove_token_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='chain',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paircontract',
            name='pair',
            field=models.CharField(choices=[('', ''), ('usdt', 'usdt'), ('usdc', 'usdc'), ('eth', 'eth'), ('bnb', 'bnb'), ('busd', 'busd'), ('avax', 'avax'), ('matic', 'matic'), ('dai', 'dai'), ('wbnb', 'wbnb')], default='', max_length=15),
        ),
    ]
