# Generated by Django 4.0.8 on 2023-11-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0025_token_chain_alter_paircontract_pair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='chain',
        ),
    ]
