# Generated by Django 4.0.8 on 2023-11-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0026_remove_token_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='chain',
            field=models.CharField(default='', max_length=255),
        ),
    ]
