# Generated by Django 4.0.8 on 2023-11-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0027_transaction_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
