# Generated by Django 4.0.8 on 2023-11-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0028_filterparams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilterParams',
            new_name='WalletFilter',
        ),
    ]
