# Generated by Django 4.0.8 on 2023-11-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0029_rename_filterparams_walletfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletfilter',
            name='min_wallets',
            field=models.IntegerField(default=0),
        ),
    ]
