# Generated by Django 4.0.8 on 2023-11-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0030_walletfilter_min_wallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletfilter',
            name='max_wallets',
            field=models.IntegerField(default=0),
        ),
    ]
