# Generated by Django 4.0.8 on 2023-11-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0031_walletfilter_max_wallets'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletfilter',
            name='min_token_wins',
            field=models.IntegerField(default=1),
        ),
    ]
