# Generated by Django 4.0.8 on 2023-11-20 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0033_onp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ONP',
        ),
    ]
