# Generated by Django 4.0.8 on 2023-12-17 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0034_delete_onp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallets.token')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('wallets.token',),
        ),
    ]
