# Generated by Django 4.0.8 on 2023-12-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0036_ownedtoken_owner_waller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownedtoken',
            old_name='owner_waller',
            new_name='owner_wallet',
        ),
    ]
