# Generated by Django 4.0.8 on 2023-12-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0037_rename_owner_waller_ownedtoken_owner_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedtoken',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
