# Generated by Django 4.0.8 on 2023-12-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0038_ownedtoken_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedtoken',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
