# Generated by Django 4.0.8 on 2023-12-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0040_alter_ownedtoken_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedtoken',
            name='balance_change',
            field=models.CharField(choices=[('increase', 'increase'), ('decrease', 'decrease')], default='', max_length=255),
        ),
    ]
