# Generated by Django 4.0.8 on 2024-01-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0043_delete_potentialgem_delete_targetwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
