# Generated by Django 4.0.8 on 2024-01-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0044_alter_transaction_amount_alter_transaction_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownedtoken',
            name='owner_wallet',
        ),
        migrations.RemoveField(
            model_name='ownedtoken',
            name='token_ptr',
        ),
        migrations.RemoveField(
            model_name='paircontract',
            name='token',
        ),
        migrations.DeleteModel(
            name='PoolContract',
        ),
        migrations.DeleteModel(
            name='OwnedToken',
        ),
        migrations.DeleteModel(
            name='PairContract',
        ),
    ]
