# Generated by Django 4.0.8 on 2024-01-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0045_remove_ownedtoken_owner_wallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('wallet', models.ManyToManyField(to='wallets.wallet')),
            ],
        ),
    ]
