# Generated by Django 4.2.9 on 2024-02-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0047_rename_address_gem_contract_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='human',
            field=models.BooleanField(default=False),
        ),
    ]
